from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Sequence


@dataclass(frozen=True)
class TensorType:
    dtype: str
    shape: Sequence[int]
    stride: Sequence[int] | None = None
    layout: str = "ND"

    def __str__(self) -> str:
        shape = list(self.shape)
        if len(shape) == 2:
            shape = [1, 1, 1, shape[0], shape[1]]
        if len(shape) != 5:
            raise ValueError("TensorType expects shape as 2D (H,W) or 5D")

        stride = list(self.stride) if self.stride is not None else [1, 1, 1, int(shape[4]), 1]
        if len(stride) != 5:
            raise ValueError("TensorType expects stride as 5D when provided")
        return (
            f"!pto.tensor<dtype={self.dtype}, shape=[{','.join(map(str, shape))}], "
            f"stride=[{','.join(map(str, stride))}], layout={self.layout}>"
        )


@dataclass(frozen=True)
class TileType:
    loc: str
    dtype: str
    rows: int
    cols: int
    blayout: str = "RowMajor"
    valid_rows: int | None = None
    valid_cols: int | None = None
    slayout: str = "NoneBox"
    fractal: int | None = None
    pad: str = "Null"

    def __str__(self) -> str:
        valid_rows = self.rows if self.valid_rows is None else self.valid_rows
        valid_cols = self.cols if self.valid_cols is None else self.valid_cols
        fractal = self.fractal
        if fractal is None:
            if self.loc == "Acc":
                fractal = 1024
            else:
                fractal = 512
        return (
            f"!pto.tile<loc={self.loc}, dtype={self.dtype}, rows={self.rows}, cols={self.cols}, "
            f"blayout={self.blayout}, valid={valid_rows}x{valid_cols}, slayout={self.slayout}, "
            f"fractal={fractal}, pad={self.pad}>"
        )


class PTOProgram:
    def __init__(self) -> None:
        self._lines: list[str] = []

    def comment(self, text: str) -> "PTOProgram":
        for line in text.splitlines():
            self._lines.append(f"; {line}" if line else ";")
        return self

    def line(self, text: str) -> "PTOProgram":
        self._lines.append(text)
        return self

    def prologue(self) -> "PTOProgram":
        return self.line("prologue")

    def epilogue(self) -> "PTOProgram":
        return self.line("epilogue")

    def arg(self, name: str, type_str: str | TensorType | TileType) -> "PTOProgram":
        if not name.startswith("%"):
            raise ValueError("arg name must start with %")
        self._lines.append(f".arg {name} : {type_str}")
        return self

    def const(self, name: str, value: str, ty: str = "index") -> "PTOProgram":
        if not name.startswith("%"):
            raise ValueError("const name must start with %")
        self._lines.append(f".const {name} = {value} : {ty}")
        return self

    def instr(self, opcode: str, operands: Iterable[str], typesig: str | None = None) -> "PTOProgram":
        op_text = f"{opcode} {', '.join(operands)}"
        if typesig:
            op_text += f" : {typesig}"
        self._lines.append(op_text)
        return self

    def emit(self) -> str:
        return "\n".join(self._lines).strip() + "\n"


def make_add16_program() -> str:
    prog = PTOProgram()
    prog.comment(
        "Generated by ptoas/python/pto_asm.py\n"
        "Vec add: z = x + y, for a single 16x16 tile (blockDim=1 in runner)."
    )
    prog.prologue()
    prog.instr("get_block_num", ["%bn"], "index")
    prog.instr("get_block_idx", ["%bid"], "index")
    prog.instr("imul", ["%r0", "%bid", "16"], "index")

    tensor = TensorType(dtype="f16", shape=[16, 16])
    tile = TileType(
        loc="Vec",
        dtype="f16",
        rows=16,
        cols=16,
    )

    prog.arg("%x", tensor).arg("%y", tensor).arg("%z", tensor)
    prog.arg("%tx", tile).arg("%ty", tile).arg("%tz", tile)

    prog.const("%addr_x", "0x0").const("%addr_y", "0x8000").const("%addr_z", "0x10000")
    prog.instr("tassign", ["%tx", "%addr_x"], "(!pto.tile<...>, index)")
    prog.instr("tassign", ["%ty", "%addr_y"], "(!pto.tile<...>, index)")
    prog.instr("tassign", ["%tz", "%addr_z"], "(!pto.tile<...>, index)")

    prog.instr("tload", ["%tx", "%x[%r0, 0]"], "(!pto.tile<...>, !pto.tensor<...>, index, index)")
    prog.instr("tload", ["%ty", "%y[%r0, 0]"], "(!pto.tile<...>, !pto.tensor<...>, index, index)")
    prog.instr("tadd", ["%tz", "%tx", "%ty"], "(!pto.tile<...>, !pto.tile<...>, !pto.tile<...>)")
    prog.instr("tstore", ["%z[%r0, 0]", "%tz"], "(!pto.tensor<...>, index, index, !pto.tile<...>)")
    prog.epilogue()
    return prog.emit()


def make_gemm16_program() -> str:
    prog = PTOProgram()
    prog.comment(
        "Generated by ptoas/python/pto_asm.py\n"
        "Cube GEMM: C = A @ B, A/B f16[16,16], C f32[16,16]."
    )
    prog.prologue()
    prog.instr("get_block_num", ["%bn"], "index")
    prog.instr("get_block_idx", ["%bid"], "index")

    a = TensorType(dtype="f16", shape=[16, 16])
    b = TensorType(dtype="f16", shape=[16, 16])
    c = TensorType(dtype="f32", shape=[16, 16])

    a_mat = TileType("Mat", "f16", 16, 16, blayout="ColMajor", slayout="RowMajor")
    b_mat = TileType("Mat", "f16", 16, 16, blayout="ColMajor", slayout="RowMajor")
    a_left = TileType("Left", "f16", 16, 16, blayout="RowMajor", slayout="RowMajor")
    b_right = TileType("Right", "f16", 16, 16, blayout="RowMajor", slayout="ColMajor")
    c_acc = TileType("Acc", "f32", 16, 16, blayout="ColMajor", slayout="RowMajor")

    prog.arg("%a", a).arg("%b", b).arg("%c", c)
    prog.arg("%a_mat", a_mat).arg("%b_mat", b_mat)
    prog.arg("%a_left", a_left).arg("%b_right", b_right).arg("%c_acc", c_acc)

    prog.const("%addr_a_mat", "0x0").const("%addr_b_mat", "0x20000")
    prog.const("%addr_a_left", "0x0").const("%addr_b_right", "0x0").const("%addr_c_acc", "0x0")

    prog.instr("tassign", ["%a_mat", "%addr_a_mat"], "(!pto.tile<...>, index)")
    prog.instr("tassign", ["%b_mat", "%addr_b_mat"], "(!pto.tile<...>, index)")
    prog.instr("tassign", ["%a_left", "%addr_a_left"], "(!pto.tile<...>, index)")
    prog.instr("tassign", ["%b_right", "%addr_b_right"], "(!pto.tile<...>, index)")
    prog.instr("tassign", ["%c_acc", "%addr_c_acc"], "(!pto.tile<...>, index)")

    prog.instr("tload", ["%a_mat", "%a[0, 0]"], "(!pto.tile<...>, !pto.tensor<...>, index, index)")
    prog.instr("tload", ["%b_mat", "%b[0, 0]"], "(!pto.tile<...>, !pto.tensor<...>, index, index)")
    prog.instr("tmov", ["%a_left", "%a_mat"], "(!pto.tile<...>, !pto.tile<...>)")
    prog.instr("tmov", ["%b_right", "%b_mat"], "(!pto.tile<...>, !pto.tile<...>)")
    prog.instr("tmatmul", ["%c_acc", "%a_left", "%b_right"], "(!pto.tile<...>, !pto.tile<...>, !pto.tile<...>)")
    prog.instr("tstore", ["%c[0, 0]", "%c_acc"], "(!pto.tensor<...>, index, index, !pto.tile<...>)")

    prog.epilogue()
    return prog.emit()
