// Generated by ptoas (mlir prototype)
#define MEMORY_BASE
#include "kernel_operator.h"
#include <pto/pto-inst.hpp>
#include <cstdint>
using namespace pto;

extern "C" __global__ AICORE void pto_kernel(GM_ADDR arg0, GM_ADDR arg1, GM_ADDR arg2) {
  using arg0_Shape = Shape<1, 1, 1, 16, 16>;
  using arg0_Stride = Stride<1, 1, 1, 16, 1>;
  using arg0_Tensor = GlobalTensor<half, arg0_Shape, arg0_Stride, Layout::ND>;
  arg0_Tensor g_arg0((__gm__ half*)arg0);

  using arg1_Shape = Shape<1, 1, 1, 16, 16>;
  using arg1_Stride = Stride<1, 1, 1, 16, 1>;
  using arg1_Tensor = GlobalTensor<half, arg1_Shape, arg1_Stride, Layout::ND>;
  arg1_Tensor g_arg1((__gm__ half*)arg1);

  using arg2_Shape = Shape<1, 1, 1, 16, 16>;
  using arg2_Stride = Stride<1, 1, 1, 16, 1>;
  using arg2_Tensor = GlobalTensor<half, arg2_Shape, arg2_Stride, Layout::ND>;
  arg2_Tensor g_arg2((__gm__ half*)arg2);

  using tx_Tile = Tile<TileType::Vec, half, 16, 16, BLayout::RowMajor, 16, 16, SLayout::NoneBox, 512, PadValue::Null>;
  tx_Tile t_tx;
  using ty_Tile = Tile<TileType::Vec, half, 16, 16, BLayout::RowMajor, 16, 16, SLayout::NoneBox, 512, PadValue::Null>;
  ty_Tile t_ty;
  using tz_Tile = Tile<TileType::Vec, half, 16, 16, BLayout::RowMajor, 16, 16, SLayout::NoneBox, 512, PadValue::Null>;
  tz_Tile t_tz;

  TASSIGN(t_tx, 0x10000);
  TASSIGN(t_ty, 0x11000);
  TASSIGN(t_tz, 0x12000);

  // prologue
  int64_t bn = static_cast<int64_t>(get_block_num());
  int64_t bid = static_cast<int64_t>(get_block_idx());
  auto cond = (bid) < (bn);
  if (cond) {
    auto m_base = (bid) * (16);
    for (int64_t m0 = 0; m0 < 16; m0 += 16) {
      for (int64_t n0 = 0; n0 < 16; n0 += 16) {
        auto m = (m_base) + (m0);
        auto* g_x_blk_base = g_arg0.data();
        decltype(g_arg0) g_x_blk(g_x_blk_base);
        auto g_x_blk_off = (0) * g_arg0.GetStride(GlobalTensorDim::DIM_0) + (0) * g_arg0.GetStride(GlobalTensorDim::DIM_1) + (0) * g_arg0.GetStride(GlobalTensorDim::DIM_2) + (m) * g_arg0.GetStride(GlobalTensorDim::DIM_3) + (n0) * g_arg0.GetStride(GlobalTensorDim::DIM_4);
        TASSIGN(g_x_blk, g_x_blk_base + g_x_blk_off);
        auto* g_y_blk_base = g_arg1.data();
        decltype(g_arg1) g_y_blk(g_y_blk_base);
        auto g_y_blk_off = (0) * g_arg1.GetStride(GlobalTensorDim::DIM_0) + (0) * g_arg1.GetStride(GlobalTensorDim::DIM_1) + (0) * g_arg1.GetStride(GlobalTensorDim::DIM_2) + (m) * g_arg1.GetStride(GlobalTensorDim::DIM_3) + (n0) * g_arg1.GetStride(GlobalTensorDim::DIM_4);
        TASSIGN(g_y_blk, g_y_blk_base + g_y_blk_off);
        auto* g_z_blk_base = g_arg2.data();
        decltype(g_arg2) g_z_blk(g_z_blk_base);
        auto g_z_blk_off = (0) * g_arg2.GetStride(GlobalTensorDim::DIM_0) + (0) * g_arg2.GetStride(GlobalTensorDim::DIM_1) + (0) * g_arg2.GetStride(GlobalTensorDim::DIM_2) + (m) * g_arg2.GetStride(GlobalTensorDim::DIM_3) + (n0) * g_arg2.GetStride(GlobalTensorDim::DIM_4);
        TASSIGN(g_z_blk, g_z_blk_base + g_z_blk_off);
        TLOAD(t_tx, g_x_blk);
        set_flag(PIPE_MTE2, PIPE_V, 0);
        TLOAD(t_ty, g_y_blk);
        set_flag(PIPE_MTE2, PIPE_V, 1);
        wait_flag(PIPE_MTE2, PIPE_V, 0);
        wait_flag(PIPE_MTE2, PIPE_V, 1);
        TADD(t_tz, t_tx, t_ty);
        set_flag(PIPE_V, PIPE_MTE3, 2);
        wait_flag(PIPE_V, PIPE_MTE3, 2);
        TSTORE(g_z_blk, t_tz);
      }
    }
  }
  // epilogue
}
