#include <cstdint>
#include <cstdio>
#include <vector>
#include <random>
#include <cmath>
#include <cstdlib>
#include <string>

// CPU-sim builtins live here when compiled with -D__CPU_SIM.
#include "pto/common/cpu_stub.hpp"

// Defined in add.cpp generated by ptoas.
extern void vec_add_kernel_2d_dynamic(float *v1, float *v2, float *v3, int32_t v4, int32_t v5);

static bool almost_equal(float a, float b, float eps = 1e-5f) {
  float diff = std::fabs(a - b);
  float scale = std::max(1.0f, std::max(std::fabs(a), std::fabs(b)));
  return diff <= eps * scale;
}

int main() {
  // Keep these in sync with PTODSL example: PTODSL/examples/aot/add_static_multicore/add_builder.py
  constexpr int rows = 1280;
  constexpr int cols = 32;
  constexpr int tile = 32;

  // The PTODSL example uses block_dim=20 with subblock_dim=2 (20 * 2 = 40 tiles).
  constexpr int blocks = 20;
  constexpr int subblocks = 2;

  std::vector<float> x(rows * cols), y(rows * cols), z(rows * cols, 0.0f), ref(rows * cols);

  std::mt19937 rng(0);
  std::uniform_real_distribution<float> dist(0.0f, 1.0f);
  for (int i = 0; i < rows * cols; ++i) {
    x[i] = dist(rng);
    y[i] = dist(rng);
    ref[i] = x[i] + y[i];
  }

  // Emulate Ascend block/subblock launch topology on CPU.
  //
  // Default: parallel launch using all available CPU threads.
  // Override for determinism:
  //   PTO_CPU_LAUNCH=sequential
  // Control threads:
  //   PTO_CPU_MAX_THREADS=8
  const char* launch_mode = std::getenv("PTO_CPU_LAUNCH");
  const char* max_threads_env = std::getenv("PTO_CPU_MAX_THREADS");
  int max_threads = 0;
  if (max_threads_env && *max_threads_env) {
    max_threads = std::atoi(max_threads_env);
  }

  auto kernel = +[](float* a, float* b, float* c, int32_t vr, int32_t vc) {
    vec_add_kernel_2d_dynamic(a, b, c, vr, vc);
  };
  constexpr int valid_row = tile;
  constexpr int valid_col = tile;

  if (launch_mode && std::string(launch_mode) == "sequential") {
    pto::cpu_sim::launch_sequential(blocks, subblocks, kernel, x.data(), y.data(), z.data(), valid_row, valid_col);
  } else {
    pto::cpu_sim::launch_parallel(blocks, subblocks, kernel, max_threads, x.data(), y.data(), z.data(), valid_row, valid_col);
  }

  // Verify.
  for (int i = 0; i < rows * cols; ++i) {
    if (!almost_equal(z[i], ref[i])) {
      std::fprintf(stderr, "Mismatch at %d: got=%f ref=%f\n", i, z[i], ref[i]);
      return 1;
    }
  }

  std::puts("PASS: CPU-sim vec_add_kernel_2d_dynamic");
  return 0;
}
